import { MyContextProvider } from './components/Mycontext'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        
        <MyContextProvider>
        {children}
        </MyContextProvider>
        
        </body>
    </html>
  )
}
